version: "2"
services:
  mysql:
    image: mysql:5.7.24
    container_name: vision-mysql
    networks:
      - vision_net
    ports:
      - "3306:3306"
    environment:
      - "TZ=${TIME_ZONE}"
      - "MYSQL_ROOT_PASSWORD=1234"
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
networks:
  vision_net:
    driver: bridge