package org.vision.wechat.persistence.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VisionClientPOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public VisionClientPOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWxClientIdIsNull() {
            addCriterion("wx_client_id is null");
            return (Criteria) this;
        }

        public Criteria andWxClientIdIsNotNull() {
            addCriterion("wx_client_id is not null");
            return (Criteria) this;
        }

        public Criteria andWxClientIdEqualTo(String value) {
            addCriterion("wx_client_id =", value, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdNotEqualTo(String value) {
            addCriterion("wx_client_id <>", value, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdGreaterThan(String value) {
            addCriterion("wx_client_id >", value, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("wx_client_id >=", value, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdLessThan(String value) {
            addCriterion("wx_client_id <", value, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdLessThanOrEqualTo(String value) {
            addCriterion("wx_client_id <=", value, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdLike(String value) {
            addCriterion("wx_client_id like", value, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdNotLike(String value) {
            addCriterion("wx_client_id not like", value, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdIn(List<String> values) {
            addCriterion("wx_client_id in", values, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdNotIn(List<String> values) {
            addCriterion("wx_client_id not in", values, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdBetween(String value1, String value2) {
            addCriterion("wx_client_id between", value1, value2, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andWxClientIdNotBetween(String value1, String value2) {
            addCriterion("wx_client_id not between", value1, value2, "wxClientId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Boolean value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Boolean value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Boolean value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Boolean value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Boolean value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Boolean value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Boolean> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Boolean> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Boolean value1, Boolean value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Boolean value1, Boolean value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNull() {
            addCriterion("id_number is null");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNotNull() {
            addCriterion("id_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumberEqualTo(String value) {
            addCriterion("id_number =", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotEqualTo(String value) {
            addCriterion("id_number <>", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThan(String value) {
            addCriterion("id_number >", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("id_number >=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThan(String value) {
            addCriterion("id_number <", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThanOrEqualTo(String value) {
            addCriterion("id_number <=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLike(String value) {
            addCriterion("id_number like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotLike(String value) {
            addCriterion("id_number not like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberIn(List<String> values) {
            addCriterion("id_number in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotIn(List<String> values) {
            addCriterion("id_number not in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberBetween(String value1, String value2) {
            addCriterion("id_number between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotBetween(String value1, String value2) {
            addCriterion("id_number not between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIsNull() {
            addCriterion("native_place is null");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIsNotNull() {
            addCriterion("native_place is not null");
            return (Criteria) this;
        }

        public Criteria andNativePlaceEqualTo(String value) {
            addCriterion("native_place =", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotEqualTo(String value) {
            addCriterion("native_place <>", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceGreaterThan(String value) {
            addCriterion("native_place >", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("native_place >=", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLessThan(String value) {
            addCriterion("native_place <", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLessThanOrEqualTo(String value) {
            addCriterion("native_place <=", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLike(String value) {
            addCriterion("native_place like", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotLike(String value) {
            addCriterion("native_place not like", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIn(List<String> values) {
            addCriterion("native_place in", values, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotIn(List<String> values) {
            addCriterion("native_place not in", values, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceBetween(String value1, String value2) {
            addCriterion("native_place between", value1, value2, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotBetween(String value1, String value2) {
            addCriterion("native_place not between", value1, value2, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(BigDecimal value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(BigDecimal value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(BigDecimal value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(BigDecimal value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<BigDecimal> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<BigDecimal> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(BigDecimal value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(BigDecimal value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(BigDecimal value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(BigDecimal value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<BigDecimal> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<BigDecimal> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("phone_number is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("phone_number =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("phone_number <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("phone_number >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("phone_number >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("phone_number <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("phone_number <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("phone_number like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("phone_number not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("phone_number in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("phone_number not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("phone_number between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("phone_number not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCountyIsNull() {
            addCriterion("county is null");
            return (Criteria) this;
        }

        public Criteria andCountyIsNotNull() {
            addCriterion("county is not null");
            return (Criteria) this;
        }

        public Criteria andCountyEqualTo(String value) {
            addCriterion("county =", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotEqualTo(String value) {
            addCriterion("county <>", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyGreaterThan(String value) {
            addCriterion("county >", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyGreaterThanOrEqualTo(String value) {
            addCriterion("county >=", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLessThan(String value) {
            addCriterion("county <", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLessThanOrEqualTo(String value) {
            addCriterion("county <=", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLike(String value) {
            addCriterion("county like", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotLike(String value) {
            addCriterion("county not like", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyIn(List<String> values) {
            addCriterion("county in", values, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotIn(List<String> values) {
            addCriterion("county not in", values, "county");
            return (Criteria) this;
        }

        public Criteria andCountyBetween(String value1, String value2) {
            addCriterion("county between", value1, value2, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotBetween(String value1, String value2) {
            addCriterion("county not between", value1, value2, "county");
            return (Criteria) this;
        }

        public Criteria andDetailAddressIsNull() {
            addCriterion("detail_address is null");
            return (Criteria) this;
        }

        public Criteria andDetailAddressIsNotNull() {
            addCriterion("detail_address is not null");
            return (Criteria) this;
        }

        public Criteria andDetailAddressEqualTo(String value) {
            addCriterion("detail_address =", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressNotEqualTo(String value) {
            addCriterion("detail_address <>", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressGreaterThan(String value) {
            addCriterion("detail_address >", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("detail_address >=", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressLessThan(String value) {
            addCriterion("detail_address <", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressLessThanOrEqualTo(String value) {
            addCriterion("detail_address <=", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressLike(String value) {
            addCriterion("detail_address like", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressNotLike(String value) {
            addCriterion("detail_address not like", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressIn(List<String> values) {
            addCriterion("detail_address in", values, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressNotIn(List<String> values) {
            addCriterion("detail_address not in", values, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressBetween(String value1, String value2) {
            addCriterion("detail_address between", value1, value2, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressNotBetween(String value1, String value2) {
            addCriterion("detail_address not between", value1, value2, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftIsNull() {
            addCriterion("vision_acuity_left is null");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftIsNotNull() {
            addCriterion("vision_acuity_left is not null");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftEqualTo(BigDecimal value) {
            addCriterion("vision_acuity_left =", value, "visionAcuityLeft");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftNotEqualTo(BigDecimal value) {
            addCriterion("vision_acuity_left <>", value, "visionAcuityLeft");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftGreaterThan(BigDecimal value) {
            addCriterion("vision_acuity_left >", value, "visionAcuityLeft");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("vision_acuity_left >=", value, "visionAcuityLeft");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftLessThan(BigDecimal value) {
            addCriterion("vision_acuity_left <", value, "visionAcuityLeft");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftLessThanOrEqualTo(BigDecimal value) {
            addCriterion("vision_acuity_left <=", value, "visionAcuityLeft");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftIn(List<BigDecimal> values) {
            addCriterion("vision_acuity_left in", values, "visionAcuityLeft");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftNotIn(List<BigDecimal> values) {
            addCriterion("vision_acuity_left not in", values, "visionAcuityLeft");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vision_acuity_left between", value1, value2, "visionAcuityLeft");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLeftNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vision_acuity_left not between", value1, value2, "visionAcuityLeft");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightIsNull() {
            addCriterion("vision_acuity_right is null");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightIsNotNull() {
            addCriterion("vision_acuity_right is not null");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightEqualTo(BigDecimal value) {
            addCriterion("vision_acuity_right =", value, "visionAcuityRight");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightNotEqualTo(BigDecimal value) {
            addCriterion("vision_acuity_right <>", value, "visionAcuityRight");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightGreaterThan(BigDecimal value) {
            addCriterion("vision_acuity_right >", value, "visionAcuityRight");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("vision_acuity_right >=", value, "visionAcuityRight");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightLessThan(BigDecimal value) {
            addCriterion("vision_acuity_right <", value, "visionAcuityRight");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("vision_acuity_right <=", value, "visionAcuityRight");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightIn(List<BigDecimal> values) {
            addCriterion("vision_acuity_right in", values, "visionAcuityRight");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightNotIn(List<BigDecimal> values) {
            addCriterion("vision_acuity_right not in", values, "visionAcuityRight");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vision_acuity_right between", value1, value2, "visionAcuityRight");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityRightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vision_acuity_right not between", value1, value2, "visionAcuityRight");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityIsNull() {
            addCriterion("vision_acuity is null");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityIsNotNull() {
            addCriterion("vision_acuity is not null");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityEqualTo(BigDecimal value) {
            addCriterion("vision_acuity =", value, "visionAcuity");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityNotEqualTo(BigDecimal value) {
            addCriterion("vision_acuity <>", value, "visionAcuity");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityGreaterThan(BigDecimal value) {
            addCriterion("vision_acuity >", value, "visionAcuity");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("vision_acuity >=", value, "visionAcuity");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLessThan(BigDecimal value) {
            addCriterion("vision_acuity <", value, "visionAcuity");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("vision_acuity <=", value, "visionAcuity");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityIn(List<BigDecimal> values) {
            addCriterion("vision_acuity in", values, "visionAcuity");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityNotIn(List<BigDecimal> values) {
            addCriterion("vision_acuity not in", values, "visionAcuity");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vision_acuity between", value1, value2, "visionAcuity");
            return (Criteria) this;
        }

        public Criteria andVisionAcuityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vision_acuity not between", value1, value2, "visionAcuity");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftIsNull() {
            addCriterion("diopters_left is null");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftIsNotNull() {
            addCriterion("diopters_left is not null");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftEqualTo(Integer value) {
            addCriterion("diopters_left =", value, "dioptersLeft");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftNotEqualTo(Integer value) {
            addCriterion("diopters_left <>", value, "dioptersLeft");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftGreaterThan(Integer value) {
            addCriterion("diopters_left >", value, "dioptersLeft");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftGreaterThanOrEqualTo(Integer value) {
            addCriterion("diopters_left >=", value, "dioptersLeft");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftLessThan(Integer value) {
            addCriterion("diopters_left <", value, "dioptersLeft");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftLessThanOrEqualTo(Integer value) {
            addCriterion("diopters_left <=", value, "dioptersLeft");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftIn(List<Integer> values) {
            addCriterion("diopters_left in", values, "dioptersLeft");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftNotIn(List<Integer> values) {
            addCriterion("diopters_left not in", values, "dioptersLeft");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftBetween(Integer value1, Integer value2) {
            addCriterion("diopters_left between", value1, value2, "dioptersLeft");
            return (Criteria) this;
        }

        public Criteria andDioptersLeftNotBetween(Integer value1, Integer value2) {
            addCriterion("diopters_left not between", value1, value2, "dioptersLeft");
            return (Criteria) this;
        }

        public Criteria andDioptersRightIsNull() {
            addCriterion("diopters_right is null");
            return (Criteria) this;
        }

        public Criteria andDioptersRightIsNotNull() {
            addCriterion("diopters_right is not null");
            return (Criteria) this;
        }

        public Criteria andDioptersRightEqualTo(Integer value) {
            addCriterion("diopters_right =", value, "dioptersRight");
            return (Criteria) this;
        }

        public Criteria andDioptersRightNotEqualTo(Integer value) {
            addCriterion("diopters_right <>", value, "dioptersRight");
            return (Criteria) this;
        }

        public Criteria andDioptersRightGreaterThan(Integer value) {
            addCriterion("diopters_right >", value, "dioptersRight");
            return (Criteria) this;
        }

        public Criteria andDioptersRightGreaterThanOrEqualTo(Integer value) {
            addCriterion("diopters_right >=", value, "dioptersRight");
            return (Criteria) this;
        }

        public Criteria andDioptersRightLessThan(Integer value) {
            addCriterion("diopters_right <", value, "dioptersRight");
            return (Criteria) this;
        }

        public Criteria andDioptersRightLessThanOrEqualTo(Integer value) {
            addCriterion("diopters_right <=", value, "dioptersRight");
            return (Criteria) this;
        }

        public Criteria andDioptersRightIn(List<Integer> values) {
            addCriterion("diopters_right in", values, "dioptersRight");
            return (Criteria) this;
        }

        public Criteria andDioptersRightNotIn(List<Integer> values) {
            addCriterion("diopters_right not in", values, "dioptersRight");
            return (Criteria) this;
        }

        public Criteria andDioptersRightBetween(Integer value1, Integer value2) {
            addCriterion("diopters_right between", value1, value2, "dioptersRight");
            return (Criteria) this;
        }

        public Criteria andDioptersRightNotBetween(Integer value1, Integer value2) {
            addCriterion("diopters_right not between", value1, value2, "dioptersRight");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftIsNull() {
            addCriterion("astigmatism_left is null");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftIsNotNull() {
            addCriterion("astigmatism_left is not null");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftEqualTo(Integer value) {
            addCriterion("astigmatism_left =", value, "astigmatismLeft");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftNotEqualTo(Integer value) {
            addCriterion("astigmatism_left <>", value, "astigmatismLeft");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftGreaterThan(Integer value) {
            addCriterion("astigmatism_left >", value, "astigmatismLeft");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftGreaterThanOrEqualTo(Integer value) {
            addCriterion("astigmatism_left >=", value, "astigmatismLeft");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftLessThan(Integer value) {
            addCriterion("astigmatism_left <", value, "astigmatismLeft");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftLessThanOrEqualTo(Integer value) {
            addCriterion("astigmatism_left <=", value, "astigmatismLeft");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftIn(List<Integer> values) {
            addCriterion("astigmatism_left in", values, "astigmatismLeft");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftNotIn(List<Integer> values) {
            addCriterion("astigmatism_left not in", values, "astigmatismLeft");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftBetween(Integer value1, Integer value2) {
            addCriterion("astigmatism_left between", value1, value2, "astigmatismLeft");
            return (Criteria) this;
        }

        public Criteria andAstigmatismLeftNotBetween(Integer value1, Integer value2) {
            addCriterion("astigmatism_left not between", value1, value2, "astigmatismLeft");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightIsNull() {
            addCriterion("astigmatism_right is null");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightIsNotNull() {
            addCriterion("astigmatism_right is not null");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightEqualTo(Integer value) {
            addCriterion("astigmatism_right =", value, "astigmatismRight");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightNotEqualTo(Integer value) {
            addCriterion("astigmatism_right <>", value, "astigmatismRight");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightGreaterThan(Integer value) {
            addCriterion("astigmatism_right >", value, "astigmatismRight");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightGreaterThanOrEqualTo(Integer value) {
            addCriterion("astigmatism_right >=", value, "astigmatismRight");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightLessThan(Integer value) {
            addCriterion("astigmatism_right <", value, "astigmatismRight");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightLessThanOrEqualTo(Integer value) {
            addCriterion("astigmatism_right <=", value, "astigmatismRight");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightIn(List<Integer> values) {
            addCriterion("astigmatism_right in", values, "astigmatismRight");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightNotIn(List<Integer> values) {
            addCriterion("astigmatism_right not in", values, "astigmatismRight");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightBetween(Integer value1, Integer value2) {
            addCriterion("astigmatism_right between", value1, value2, "astigmatismRight");
            return (Criteria) this;
        }

        public Criteria andAstigmatismRightNotBetween(Integer value1, Integer value2) {
            addCriterion("astigmatism_right not between", value1, value2, "astigmatismRight");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftIsNull() {
            addCriterion("joint_luminosity_left is null");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftIsNotNull() {
            addCriterion("joint_luminosity_left is not null");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftEqualTo(Integer value) {
            addCriterion("joint_luminosity_left =", value, "jointLuminosityLeft");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftNotEqualTo(Integer value) {
            addCriterion("joint_luminosity_left <>", value, "jointLuminosityLeft");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftGreaterThan(Integer value) {
            addCriterion("joint_luminosity_left >", value, "jointLuminosityLeft");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftGreaterThanOrEqualTo(Integer value) {
            addCriterion("joint_luminosity_left >=", value, "jointLuminosityLeft");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftLessThan(Integer value) {
            addCriterion("joint_luminosity_left <", value, "jointLuminosityLeft");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftLessThanOrEqualTo(Integer value) {
            addCriterion("joint_luminosity_left <=", value, "jointLuminosityLeft");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftIn(List<Integer> values) {
            addCriterion("joint_luminosity_left in", values, "jointLuminosityLeft");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftNotIn(List<Integer> values) {
            addCriterion("joint_luminosity_left not in", values, "jointLuminosityLeft");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftBetween(Integer value1, Integer value2) {
            addCriterion("joint_luminosity_left between", value1, value2, "jointLuminosityLeft");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityLeftNotBetween(Integer value1, Integer value2) {
            addCriterion("joint_luminosity_left not between", value1, value2, "jointLuminosityLeft");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightIsNull() {
            addCriterion("joint_luminosity_right is null");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightIsNotNull() {
            addCriterion("joint_luminosity_right is not null");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightEqualTo(Integer value) {
            addCriterion("joint_luminosity_right =", value, "jointLuminosityRight");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightNotEqualTo(Integer value) {
            addCriterion("joint_luminosity_right <>", value, "jointLuminosityRight");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightGreaterThan(Integer value) {
            addCriterion("joint_luminosity_right >", value, "jointLuminosityRight");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightGreaterThanOrEqualTo(Integer value) {
            addCriterion("joint_luminosity_right >=", value, "jointLuminosityRight");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightLessThan(Integer value) {
            addCriterion("joint_luminosity_right <", value, "jointLuminosityRight");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightLessThanOrEqualTo(Integer value) {
            addCriterion("joint_luminosity_right <=", value, "jointLuminosityRight");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightIn(List<Integer> values) {
            addCriterion("joint_luminosity_right in", values, "jointLuminosityRight");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightNotIn(List<Integer> values) {
            addCriterion("joint_luminosity_right not in", values, "jointLuminosityRight");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightBetween(Integer value1, Integer value2) {
            addCriterion("joint_luminosity_right between", value1, value2, "jointLuminosityRight");
            return (Criteria) this;
        }

        public Criteria andJointLuminosityRightNotBetween(Integer value1, Integer value2) {
            addCriterion("joint_luminosity_right not between", value1, value2, "jointLuminosityRight");
            return (Criteria) this;
        }

        public Criteria andAxisLeftIsNull() {
            addCriterion("axis_left is null");
            return (Criteria) this;
        }

        public Criteria andAxisLeftIsNotNull() {
            addCriterion("axis_left is not null");
            return (Criteria) this;
        }

        public Criteria andAxisLeftEqualTo(Integer value) {
            addCriterion("axis_left =", value, "axisLeft");
            return (Criteria) this;
        }

        public Criteria andAxisLeftNotEqualTo(Integer value) {
            addCriterion("axis_left <>", value, "axisLeft");
            return (Criteria) this;
        }

        public Criteria andAxisLeftGreaterThan(Integer value) {
            addCriterion("axis_left >", value, "axisLeft");
            return (Criteria) this;
        }

        public Criteria andAxisLeftGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_left >=", value, "axisLeft");
            return (Criteria) this;
        }

        public Criteria andAxisLeftLessThan(Integer value) {
            addCriterion("axis_left <", value, "axisLeft");
            return (Criteria) this;
        }

        public Criteria andAxisLeftLessThanOrEqualTo(Integer value) {
            addCriterion("axis_left <=", value, "axisLeft");
            return (Criteria) this;
        }

        public Criteria andAxisLeftIn(List<Integer> values) {
            addCriterion("axis_left in", values, "axisLeft");
            return (Criteria) this;
        }

        public Criteria andAxisLeftNotIn(List<Integer> values) {
            addCriterion("axis_left not in", values, "axisLeft");
            return (Criteria) this;
        }

        public Criteria andAxisLeftBetween(Integer value1, Integer value2) {
            addCriterion("axis_left between", value1, value2, "axisLeft");
            return (Criteria) this;
        }

        public Criteria andAxisLeftNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_left not between", value1, value2, "axisLeft");
            return (Criteria) this;
        }

        public Criteria andAxisRightIsNull() {
            addCriterion("axis_right is null");
            return (Criteria) this;
        }

        public Criteria andAxisRightIsNotNull() {
            addCriterion("axis_right is not null");
            return (Criteria) this;
        }

        public Criteria andAxisRightEqualTo(Integer value) {
            addCriterion("axis_right =", value, "axisRight");
            return (Criteria) this;
        }

        public Criteria andAxisRightNotEqualTo(Integer value) {
            addCriterion("axis_right <>", value, "axisRight");
            return (Criteria) this;
        }

        public Criteria andAxisRightGreaterThan(Integer value) {
            addCriterion("axis_right >", value, "axisRight");
            return (Criteria) this;
        }

        public Criteria andAxisRightGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_right >=", value, "axisRight");
            return (Criteria) this;
        }

        public Criteria andAxisRightLessThan(Integer value) {
            addCriterion("axis_right <", value, "axisRight");
            return (Criteria) this;
        }

        public Criteria andAxisRightLessThanOrEqualTo(Integer value) {
            addCriterion("axis_right <=", value, "axisRight");
            return (Criteria) this;
        }

        public Criteria andAxisRightIn(List<Integer> values) {
            addCriterion("axis_right in", values, "axisRight");
            return (Criteria) this;
        }

        public Criteria andAxisRightNotIn(List<Integer> values) {
            addCriterion("axis_right not in", values, "axisRight");
            return (Criteria) this;
        }

        public Criteria andAxisRightBetween(Integer value1, Integer value2) {
            addCriterion("axis_right between", value1, value2, "axisRight");
            return (Criteria) this;
        }

        public Criteria andAxisRightNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_right not between", value1, value2, "axisRight");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceIsNull() {
            addCriterion("pupil_distance is null");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceIsNotNull() {
            addCriterion("pupil_distance is not null");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceEqualTo(Integer value) {
            addCriterion("pupil_distance =", value, "pupilDistance");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceNotEqualTo(Integer value) {
            addCriterion("pupil_distance <>", value, "pupilDistance");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceGreaterThan(Integer value) {
            addCriterion("pupil_distance >", value, "pupilDistance");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceGreaterThanOrEqualTo(Integer value) {
            addCriterion("pupil_distance >=", value, "pupilDistance");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceLessThan(Integer value) {
            addCriterion("pupil_distance <", value, "pupilDistance");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceLessThanOrEqualTo(Integer value) {
            addCriterion("pupil_distance <=", value, "pupilDistance");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceIn(List<Integer> values) {
            addCriterion("pupil_distance in", values, "pupilDistance");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceNotIn(List<Integer> values) {
            addCriterion("pupil_distance not in", values, "pupilDistance");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceBetween(Integer value1, Integer value2) {
            addCriterion("pupil_distance between", value1, value2, "pupilDistance");
            return (Criteria) this;
        }

        public Criteria andPupilDistanceNotBetween(Integer value1, Integer value2) {
            addCriterion("pupil_distance not between", value1, value2, "pupilDistance");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("modified_time is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("modified_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("modified_time =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("modified_time <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("modified_time >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_time >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("modified_time <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("modified_time <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("modified_time in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("modified_time not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("modified_time between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("modified_time not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vision_client
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 04 15:29:41 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}