package org.vision.wechat.persistence.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table vision_client
 */
@Data
public class VisionClientPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.id
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private String id;

    /**
     * Database Column Remarks:
     *   微信注册用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.wx_client_id
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private String wxClientId;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.name
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private String name;

    /**
     * Database Column Remarks:
     *   0:未知,1:男性,2:女性
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.gender
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Boolean gender;

    /**
     * Database Column Remarks:
     *   -1: 年龄保密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.age
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.id_number
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private String idNumber;

    /**
     * Database Column Remarks:
     *   籍贯
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.native_place
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private String nativePlace;

    /**
     * Database Column Remarks:
     *   身高
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.height
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private BigDecimal height;

    /**
     * Database Column Remarks:
     *   体重
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.weight
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private BigDecimal weight;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.birthday
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.phone_number
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private String phoneNumber;

    /**
     * Database Column Remarks:
     *   省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.province
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private String province;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.city
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private String city;

    /**
     * Database Column Remarks:
     *   区县
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.county
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private String county;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.detail_address
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private String detailAddress;

    /**
     * Database Column Remarks:
     *   裸眼视力-左
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.vision_acuity_left
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private BigDecimal visionAcuityLeft;

    /**
     * Database Column Remarks:
     *   裸眼视力-右
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.vision_acuity_right
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private BigDecimal visionAcuityRight;

    /**
     * Database Column Remarks:
     *   裸眼视力
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.vision_acuity
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private BigDecimal visionAcuity;

    /**
     * Database Column Remarks:
     *   屈光度-左
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.diopters_left
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Integer dioptersLeft;

    /**
     * Database Column Remarks:
     *   屈光度-右
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.diopters_right
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Integer dioptersRight;

    /**
     * Database Column Remarks:
     *   散光度-左
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.astigmatism_left
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Integer astigmatismLeft;

    /**
     * Database Column Remarks:
     *   散光度_右
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.astigmatism_right
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Integer astigmatismRight;

    /**
     * Database Column Remarks:
     *   联合光度-左
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.joint_luminosity_left
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Integer jointLuminosityLeft;

    /**
     * Database Column Remarks:
     *   联合光度-右
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.joint_luminosity_right
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Integer jointLuminosityRight;

    /**
     * Database Column Remarks:
     *   轴位-左
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.axis_left
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Integer axisLeft;

    /**
     * Database Column Remarks:
     *   轴位-右
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.axis_right
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    private Integer axisRight;

    /**
     * Database Column Remarks:
     *   瞳距
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.pupil_distance
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    private Integer pupilDistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.created_time
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.modified_time
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    private static final long serialVersionUID = 1L;
}