package org.vision.wechat.persistence.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VisionCheckRecordPOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public VisionCheckRecordPOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdIsNull() {
            addCriterion("vision_client_id is null");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdIsNotNull() {
            addCriterion("vision_client_id is not null");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdEqualTo(String value) {
            addCriterion("vision_client_id =", value, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdNotEqualTo(String value) {
            addCriterion("vision_client_id <>", value, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdGreaterThan(String value) {
            addCriterion("vision_client_id >", value, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("vision_client_id >=", value, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdLessThan(String value) {
            addCriterion("vision_client_id <", value, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdLessThanOrEqualTo(String value) {
            addCriterion("vision_client_id <=", value, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdLike(String value) {
            addCriterion("vision_client_id like", value, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdNotLike(String value) {
            addCriterion("vision_client_id not like", value, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdIn(List<String> values) {
            addCriterion("vision_client_id in", values, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdNotIn(List<String> values) {
            addCriterion("vision_client_id not in", values, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdBetween(String value1, String value2) {
            addCriterion("vision_client_id between", value1, value2, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andVisionClientIdNotBetween(String value1, String value2) {
            addCriterion("vision_client_id not between", value1, value2, "visionClientId");
            return (Criteria) this;
        }

        public Criteria andEyeTypeIsNull() {
            addCriterion("eye_type is null");
            return (Criteria) this;
        }

        public Criteria andEyeTypeIsNotNull() {
            addCriterion("eye_type is not null");
            return (Criteria) this;
        }

        public Criteria andEyeTypeEqualTo(String value) {
            addCriterion("eye_type =", value, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeNotEqualTo(String value) {
            addCriterion("eye_type <>", value, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeGreaterThan(String value) {
            addCriterion("eye_type >", value, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("eye_type >=", value, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeLessThan(String value) {
            addCriterion("eye_type <", value, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeLessThanOrEqualTo(String value) {
            addCriterion("eye_type <=", value, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeLike(String value) {
            addCriterion("eye_type like", value, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeNotLike(String value) {
            addCriterion("eye_type not like", value, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeIn(List<String> values) {
            addCriterion("eye_type in", values, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeNotIn(List<String> values) {
            addCriterion("eye_type not in", values, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeBetween(String value1, String value2) {
            addCriterion("eye_type between", value1, value2, "eyeType");
            return (Criteria) this;
        }

        public Criteria andEyeTypeNotBetween(String value1, String value2) {
            addCriterion("eye_type not between", value1, value2, "eyeType");
            return (Criteria) this;
        }

        public Criteria andCheckDateIsNull() {
            addCriterion("check_date is null");
            return (Criteria) this;
        }

        public Criteria andCheckDateIsNotNull() {
            addCriterion("check_date is not null");
            return (Criteria) this;
        }

        public Criteria andCheckDateEqualTo(Date value) {
            addCriterion("check_date =", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotEqualTo(Date value) {
            addCriterion("check_date <>", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateGreaterThan(Date value) {
            addCriterion("check_date >", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateGreaterThanOrEqualTo(Date value) {
            addCriterion("check_date >=", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLessThan(Date value) {
            addCriterion("check_date <", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLessThanOrEqualTo(Date value) {
            addCriterion("check_date <=", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateIn(List<Date> values) {
            addCriterion("check_date in", values, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotIn(List<Date> values) {
            addCriterion("check_date not in", values, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateBetween(Date value1, Date value2) {
            addCriterion("check_date between", value1, value2, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotBetween(Date value1, Date value2) {
            addCriterion("check_date not between", value1, value2, "checkDate");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNull() {
            addCriterion("data_type is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNotNull() {
            addCriterion("data_type is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeEqualTo(Boolean value) {
            addCriterion("data_type =", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotEqualTo(Boolean value) {
            addCriterion("data_type <>", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThan(Boolean value) {
            addCriterion("data_type >", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("data_type >=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThan(Boolean value) {
            addCriterion("data_type <", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("data_type <=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeIn(List<Boolean> values) {
            addCriterion("data_type in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotIn(List<Boolean> values) {
            addCriterion("data_type not in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("data_type between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("data_type not between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andPictureFileIsNull() {
            addCriterion("picture_file is null");
            return (Criteria) this;
        }

        public Criteria andPictureFileIsNotNull() {
            addCriterion("picture_file is not null");
            return (Criteria) this;
        }

        public Criteria andPictureFileEqualTo(String value) {
            addCriterion("picture_file =", value, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileNotEqualTo(String value) {
            addCriterion("picture_file <>", value, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileGreaterThan(String value) {
            addCriterion("picture_file >", value, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileGreaterThanOrEqualTo(String value) {
            addCriterion("picture_file >=", value, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileLessThan(String value) {
            addCriterion("picture_file <", value, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileLessThanOrEqualTo(String value) {
            addCriterion("picture_file <=", value, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileLike(String value) {
            addCriterion("picture_file like", value, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileNotLike(String value) {
            addCriterion("picture_file not like", value, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileIn(List<String> values) {
            addCriterion("picture_file in", values, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileNotIn(List<String> values) {
            addCriterion("picture_file not in", values, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileBetween(String value1, String value2) {
            addCriterion("picture_file between", value1, value2, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPictureFileNotBetween(String value1, String value2) {
            addCriterion("picture_file not between", value1, value2, "pictureFile");
            return (Criteria) this;
        }

        public Criteria andPupilIsNull() {
            addCriterion("pupil is null");
            return (Criteria) this;
        }

        public Criteria andPupilIsNotNull() {
            addCriterion("pupil is not null");
            return (Criteria) this;
        }

        public Criteria andPupilEqualTo(BigDecimal value) {
            addCriterion("pupil =", value, "pupil");
            return (Criteria) this;
        }

        public Criteria andPupilNotEqualTo(BigDecimal value) {
            addCriterion("pupil <>", value, "pupil");
            return (Criteria) this;
        }

        public Criteria andPupilGreaterThan(BigDecimal value) {
            addCriterion("pupil >", value, "pupil");
            return (Criteria) this;
        }

        public Criteria andPupilGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pupil >=", value, "pupil");
            return (Criteria) this;
        }

        public Criteria andPupilLessThan(BigDecimal value) {
            addCriterion("pupil <", value, "pupil");
            return (Criteria) this;
        }

        public Criteria andPupilLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pupil <=", value, "pupil");
            return (Criteria) this;
        }

        public Criteria andPupilIn(List<BigDecimal> values) {
            addCriterion("pupil in", values, "pupil");
            return (Criteria) this;
        }

        public Criteria andPupilNotIn(List<BigDecimal> values) {
            addCriterion("pupil not in", values, "pupil");
            return (Criteria) this;
        }

        public Criteria andPupilBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pupil between", value1, value2, "pupil");
            return (Criteria) this;
        }

        public Criteria andPupilNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pupil not between", value1, value2, "pupil");
            return (Criteria) this;
        }

        public Criteria andSe1IsNull() {
            addCriterion("se1 is null");
            return (Criteria) this;
        }

        public Criteria andSe1IsNotNull() {
            addCriterion("se1 is not null");
            return (Criteria) this;
        }

        public Criteria andSe1EqualTo(BigDecimal value) {
            addCriterion("se1 =", value, "se1");
            return (Criteria) this;
        }

        public Criteria andSe1NotEqualTo(BigDecimal value) {
            addCriterion("se1 <>", value, "se1");
            return (Criteria) this;
        }

        public Criteria andSe1GreaterThan(BigDecimal value) {
            addCriterion("se1 >", value, "se1");
            return (Criteria) this;
        }

        public Criteria andSe1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("se1 >=", value, "se1");
            return (Criteria) this;
        }

        public Criteria andSe1LessThan(BigDecimal value) {
            addCriterion("se1 <", value, "se1");
            return (Criteria) this;
        }

        public Criteria andSe1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("se1 <=", value, "se1");
            return (Criteria) this;
        }

        public Criteria andSe1In(List<BigDecimal> values) {
            addCriterion("se1 in", values, "se1");
            return (Criteria) this;
        }

        public Criteria andSe1NotIn(List<BigDecimal> values) {
            addCriterion("se1 not in", values, "se1");
            return (Criteria) this;
        }

        public Criteria andSe1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("se1 between", value1, value2, "se1");
            return (Criteria) this;
        }

        public Criteria andSe1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("se1 not between", value1, value2, "se1");
            return (Criteria) this;
        }

        public Criteria andDs1IsNull() {
            addCriterion("ds1 is null");
            return (Criteria) this;
        }

        public Criteria andDs1IsNotNull() {
            addCriterion("ds1 is not null");
            return (Criteria) this;
        }

        public Criteria andDs1EqualTo(BigDecimal value) {
            addCriterion("ds1 =", value, "ds1");
            return (Criteria) this;
        }

        public Criteria andDs1NotEqualTo(BigDecimal value) {
            addCriterion("ds1 <>", value, "ds1");
            return (Criteria) this;
        }

        public Criteria andDs1GreaterThan(BigDecimal value) {
            addCriterion("ds1 >", value, "ds1");
            return (Criteria) this;
        }

        public Criteria andDs1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ds1 >=", value, "ds1");
            return (Criteria) this;
        }

        public Criteria andDs1LessThan(BigDecimal value) {
            addCriterion("ds1 <", value, "ds1");
            return (Criteria) this;
        }

        public Criteria andDs1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("ds1 <=", value, "ds1");
            return (Criteria) this;
        }

        public Criteria andDs1In(List<BigDecimal> values) {
            addCriterion("ds1 in", values, "ds1");
            return (Criteria) this;
        }

        public Criteria andDs1NotIn(List<BigDecimal> values) {
            addCriterion("ds1 not in", values, "ds1");
            return (Criteria) this;
        }

        public Criteria andDs1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("ds1 between", value1, value2, "ds1");
            return (Criteria) this;
        }

        public Criteria andDs1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ds1 not between", value1, value2, "ds1");
            return (Criteria) this;
        }

        public Criteria andDc1IsNull() {
            addCriterion("dc1 is null");
            return (Criteria) this;
        }

        public Criteria andDc1IsNotNull() {
            addCriterion("dc1 is not null");
            return (Criteria) this;
        }

        public Criteria andDc1EqualTo(BigDecimal value) {
            addCriterion("dc1 =", value, "dc1");
            return (Criteria) this;
        }

        public Criteria andDc1NotEqualTo(BigDecimal value) {
            addCriterion("dc1 <>", value, "dc1");
            return (Criteria) this;
        }

        public Criteria andDc1GreaterThan(BigDecimal value) {
            addCriterion("dc1 >", value, "dc1");
            return (Criteria) this;
        }

        public Criteria andDc1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dc1 >=", value, "dc1");
            return (Criteria) this;
        }

        public Criteria andDc1LessThan(BigDecimal value) {
            addCriterion("dc1 <", value, "dc1");
            return (Criteria) this;
        }

        public Criteria andDc1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("dc1 <=", value, "dc1");
            return (Criteria) this;
        }

        public Criteria andDc1In(List<BigDecimal> values) {
            addCriterion("dc1 in", values, "dc1");
            return (Criteria) this;
        }

        public Criteria andDc1NotIn(List<BigDecimal> values) {
            addCriterion("dc1 not in", values, "dc1");
            return (Criteria) this;
        }

        public Criteria andDc1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("dc1 between", value1, value2, "dc1");
            return (Criteria) this;
        }

        public Criteria andDc1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dc1 not between", value1, value2, "dc1");
            return (Criteria) this;
        }

        public Criteria andAxis1IsNull() {
            addCriterion("axis1 is null");
            return (Criteria) this;
        }

        public Criteria andAxis1IsNotNull() {
            addCriterion("axis1 is not null");
            return (Criteria) this;
        }

        public Criteria andAxis1EqualTo(Integer value) {
            addCriterion("axis1 =", value, "axis1");
            return (Criteria) this;
        }

        public Criteria andAxis1NotEqualTo(Integer value) {
            addCriterion("axis1 <>", value, "axis1");
            return (Criteria) this;
        }

        public Criteria andAxis1GreaterThan(Integer value) {
            addCriterion("axis1 >", value, "axis1");
            return (Criteria) this;
        }

        public Criteria andAxis1GreaterThanOrEqualTo(Integer value) {
            addCriterion("axis1 >=", value, "axis1");
            return (Criteria) this;
        }

        public Criteria andAxis1LessThan(Integer value) {
            addCriterion("axis1 <", value, "axis1");
            return (Criteria) this;
        }

        public Criteria andAxis1LessThanOrEqualTo(Integer value) {
            addCriterion("axis1 <=", value, "axis1");
            return (Criteria) this;
        }

        public Criteria andAxis1In(List<Integer> values) {
            addCriterion("axis1 in", values, "axis1");
            return (Criteria) this;
        }

        public Criteria andAxis1NotIn(List<Integer> values) {
            addCriterion("axis1 not in", values, "axis1");
            return (Criteria) this;
        }

        public Criteria andAxis1Between(Integer value1, Integer value2) {
            addCriterion("axis1 between", value1, value2, "axis1");
            return (Criteria) this;
        }

        public Criteria andAxis1NotBetween(Integer value1, Integer value2) {
            addCriterion("axis1 not between", value1, value2, "axis1");
            return (Criteria) this;
        }

        public Criteria andSe2IsNull() {
            addCriterion("se2 is null");
            return (Criteria) this;
        }

        public Criteria andSe2IsNotNull() {
            addCriterion("se2 is not null");
            return (Criteria) this;
        }

        public Criteria andSe2EqualTo(BigDecimal value) {
            addCriterion("se2 =", value, "se2");
            return (Criteria) this;
        }

        public Criteria andSe2NotEqualTo(BigDecimal value) {
            addCriterion("se2 <>", value, "se2");
            return (Criteria) this;
        }

        public Criteria andSe2GreaterThan(BigDecimal value) {
            addCriterion("se2 >", value, "se2");
            return (Criteria) this;
        }

        public Criteria andSe2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("se2 >=", value, "se2");
            return (Criteria) this;
        }

        public Criteria andSe2LessThan(BigDecimal value) {
            addCriterion("se2 <", value, "se2");
            return (Criteria) this;
        }

        public Criteria andSe2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("se2 <=", value, "se2");
            return (Criteria) this;
        }

        public Criteria andSe2In(List<BigDecimal> values) {
            addCriterion("se2 in", values, "se2");
            return (Criteria) this;
        }

        public Criteria andSe2NotIn(List<BigDecimal> values) {
            addCriterion("se2 not in", values, "se2");
            return (Criteria) this;
        }

        public Criteria andSe2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("se2 between", value1, value2, "se2");
            return (Criteria) this;
        }

        public Criteria andSe2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("se2 not between", value1, value2, "se2");
            return (Criteria) this;
        }

        public Criteria andDs2IsNull() {
            addCriterion("ds2 is null");
            return (Criteria) this;
        }

        public Criteria andDs2IsNotNull() {
            addCriterion("ds2 is not null");
            return (Criteria) this;
        }

        public Criteria andDs2EqualTo(BigDecimal value) {
            addCriterion("ds2 =", value, "ds2");
            return (Criteria) this;
        }

        public Criteria andDs2NotEqualTo(BigDecimal value) {
            addCriterion("ds2 <>", value, "ds2");
            return (Criteria) this;
        }

        public Criteria andDs2GreaterThan(BigDecimal value) {
            addCriterion("ds2 >", value, "ds2");
            return (Criteria) this;
        }

        public Criteria andDs2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ds2 >=", value, "ds2");
            return (Criteria) this;
        }

        public Criteria andDs2LessThan(BigDecimal value) {
            addCriterion("ds2 <", value, "ds2");
            return (Criteria) this;
        }

        public Criteria andDs2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("ds2 <=", value, "ds2");
            return (Criteria) this;
        }

        public Criteria andDs2In(List<BigDecimal> values) {
            addCriterion("ds2 in", values, "ds2");
            return (Criteria) this;
        }

        public Criteria andDs2NotIn(List<BigDecimal> values) {
            addCriterion("ds2 not in", values, "ds2");
            return (Criteria) this;
        }

        public Criteria andDs2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("ds2 between", value1, value2, "ds2");
            return (Criteria) this;
        }

        public Criteria andDs2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ds2 not between", value1, value2, "ds2");
            return (Criteria) this;
        }

        public Criteria andDc2IsNull() {
            addCriterion("dc2 is null");
            return (Criteria) this;
        }

        public Criteria andDc2IsNotNull() {
            addCriterion("dc2 is not null");
            return (Criteria) this;
        }

        public Criteria andDc2EqualTo(BigDecimal value) {
            addCriterion("dc2 =", value, "dc2");
            return (Criteria) this;
        }

        public Criteria andDc2NotEqualTo(BigDecimal value) {
            addCriterion("dc2 <>", value, "dc2");
            return (Criteria) this;
        }

        public Criteria andDc2GreaterThan(BigDecimal value) {
            addCriterion("dc2 >", value, "dc2");
            return (Criteria) this;
        }

        public Criteria andDc2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dc2 >=", value, "dc2");
            return (Criteria) this;
        }

        public Criteria andDc2LessThan(BigDecimal value) {
            addCriterion("dc2 <", value, "dc2");
            return (Criteria) this;
        }

        public Criteria andDc2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("dc2 <=", value, "dc2");
            return (Criteria) this;
        }

        public Criteria andDc2In(List<BigDecimal> values) {
            addCriterion("dc2 in", values, "dc2");
            return (Criteria) this;
        }

        public Criteria andDc2NotIn(List<BigDecimal> values) {
            addCriterion("dc2 not in", values, "dc2");
            return (Criteria) this;
        }

        public Criteria andDc2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("dc2 between", value1, value2, "dc2");
            return (Criteria) this;
        }

        public Criteria andDc2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dc2 not between", value1, value2, "dc2");
            return (Criteria) this;
        }

        public Criteria andAxis2IsNull() {
            addCriterion("axis2 is null");
            return (Criteria) this;
        }

        public Criteria andAxis2IsNotNull() {
            addCriterion("axis2 is not null");
            return (Criteria) this;
        }

        public Criteria andAxis2EqualTo(Integer value) {
            addCriterion("axis2 =", value, "axis2");
            return (Criteria) this;
        }

        public Criteria andAxis2NotEqualTo(Integer value) {
            addCriterion("axis2 <>", value, "axis2");
            return (Criteria) this;
        }

        public Criteria andAxis2GreaterThan(Integer value) {
            addCriterion("axis2 >", value, "axis2");
            return (Criteria) this;
        }

        public Criteria andAxis2GreaterThanOrEqualTo(Integer value) {
            addCriterion("axis2 >=", value, "axis2");
            return (Criteria) this;
        }

        public Criteria andAxis2LessThan(Integer value) {
            addCriterion("axis2 <", value, "axis2");
            return (Criteria) this;
        }

        public Criteria andAxis2LessThanOrEqualTo(Integer value) {
            addCriterion("axis2 <=", value, "axis2");
            return (Criteria) this;
        }

        public Criteria andAxis2In(List<Integer> values) {
            addCriterion("axis2 in", values, "axis2");
            return (Criteria) this;
        }

        public Criteria andAxis2NotIn(List<Integer> values) {
            addCriterion("axis2 not in", values, "axis2");
            return (Criteria) this;
        }

        public Criteria andAxis2Between(Integer value1, Integer value2) {
            addCriterion("axis2 between", value1, value2, "axis2");
            return (Criteria) this;
        }

        public Criteria andAxis2NotBetween(Integer value1, Integer value2) {
            addCriterion("axis2 not between", value1, value2, "axis2");
            return (Criteria) this;
        }

        public Criteria andPdIsNull() {
            addCriterion("pd is null");
            return (Criteria) this;
        }

        public Criteria andPdIsNotNull() {
            addCriterion("pd is not null");
            return (Criteria) this;
        }

        public Criteria andPdEqualTo(Integer value) {
            addCriterion("pd =", value, "pd");
            return (Criteria) this;
        }

        public Criteria andPdNotEqualTo(Integer value) {
            addCriterion("pd <>", value, "pd");
            return (Criteria) this;
        }

        public Criteria andPdGreaterThan(Integer value) {
            addCriterion("pd >", value, "pd");
            return (Criteria) this;
        }

        public Criteria andPdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pd >=", value, "pd");
            return (Criteria) this;
        }

        public Criteria andPdLessThan(Integer value) {
            addCriterion("pd <", value, "pd");
            return (Criteria) this;
        }

        public Criteria andPdLessThanOrEqualTo(Integer value) {
            addCriterion("pd <=", value, "pd");
            return (Criteria) this;
        }

        public Criteria andPdIn(List<Integer> values) {
            addCriterion("pd in", values, "pd");
            return (Criteria) this;
        }

        public Criteria andPdNotIn(List<Integer> values) {
            addCriterion("pd not in", values, "pd");
            return (Criteria) this;
        }

        public Criteria andPdBetween(Integer value1, Integer value2) {
            addCriterion("pd between", value1, value2, "pd");
            return (Criteria) this;
        }

        public Criteria andPdNotBetween(Integer value1, Integer value2) {
            addCriterion("pd not between", value1, value2, "pd");
            return (Criteria) this;
        }

        public Criteria andMmHgIsNull() {
            addCriterion("mm_hg is null");
            return (Criteria) this;
        }

        public Criteria andMmHgIsNotNull() {
            addCriterion("mm_hg is not null");
            return (Criteria) this;
        }

        public Criteria andMmHgEqualTo(BigDecimal value) {
            addCriterion("mm_hg =", value, "mmHg");
            return (Criteria) this;
        }

        public Criteria andMmHgNotEqualTo(BigDecimal value) {
            addCriterion("mm_hg <>", value, "mmHg");
            return (Criteria) this;
        }

        public Criteria andMmHgGreaterThan(BigDecimal value) {
            addCriterion("mm_hg >", value, "mmHg");
            return (Criteria) this;
        }

        public Criteria andMmHgGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mm_hg >=", value, "mmHg");
            return (Criteria) this;
        }

        public Criteria andMmHgLessThan(BigDecimal value) {
            addCriterion("mm_hg <", value, "mmHg");
            return (Criteria) this;
        }

        public Criteria andMmHgLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mm_hg <=", value, "mmHg");
            return (Criteria) this;
        }

        public Criteria andMmHgIn(List<BigDecimal> values) {
            addCriterion("mm_hg in", values, "mmHg");
            return (Criteria) this;
        }

        public Criteria andMmHgNotIn(List<BigDecimal> values) {
            addCriterion("mm_hg not in", values, "mmHg");
            return (Criteria) this;
        }

        public Criteria andMmHgBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mm_hg between", value1, value2, "mmHg");
            return (Criteria) this;
        }

        public Criteria andMmHgNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mm_hg not between", value1, value2, "mmHg");
            return (Criteria) this;
        }

        public Criteria andGazeHIsNull() {
            addCriterion("gaze_h is null");
            return (Criteria) this;
        }

        public Criteria andGazeHIsNotNull() {
            addCriterion("gaze_h is not null");
            return (Criteria) this;
        }

        public Criteria andGazeHEqualTo(Integer value) {
            addCriterion("gaze_h =", value, "gazeH");
            return (Criteria) this;
        }

        public Criteria andGazeHNotEqualTo(Integer value) {
            addCriterion("gaze_h <>", value, "gazeH");
            return (Criteria) this;
        }

        public Criteria andGazeHGreaterThan(Integer value) {
            addCriterion("gaze_h >", value, "gazeH");
            return (Criteria) this;
        }

        public Criteria andGazeHGreaterThanOrEqualTo(Integer value) {
            addCriterion("gaze_h >=", value, "gazeH");
            return (Criteria) this;
        }

        public Criteria andGazeHLessThan(Integer value) {
            addCriterion("gaze_h <", value, "gazeH");
            return (Criteria) this;
        }

        public Criteria andGazeHLessThanOrEqualTo(Integer value) {
            addCriterion("gaze_h <=", value, "gazeH");
            return (Criteria) this;
        }

        public Criteria andGazeHIn(List<Integer> values) {
            addCriterion("gaze_h in", values, "gazeH");
            return (Criteria) this;
        }

        public Criteria andGazeHNotIn(List<Integer> values) {
            addCriterion("gaze_h not in", values, "gazeH");
            return (Criteria) this;
        }

        public Criteria andGazeHBetween(Integer value1, Integer value2) {
            addCriterion("gaze_h between", value1, value2, "gazeH");
            return (Criteria) this;
        }

        public Criteria andGazeHNotBetween(Integer value1, Integer value2) {
            addCriterion("gaze_h not between", value1, value2, "gazeH");
            return (Criteria) this;
        }

        public Criteria andGazeVIsNull() {
            addCriterion("gaze_v is null");
            return (Criteria) this;
        }

        public Criteria andGazeVIsNotNull() {
            addCriterion("gaze_v is not null");
            return (Criteria) this;
        }

        public Criteria andGazeVEqualTo(Integer value) {
            addCriterion("gaze_v =", value, "gazeV");
            return (Criteria) this;
        }

        public Criteria andGazeVNotEqualTo(Integer value) {
            addCriterion("gaze_v <>", value, "gazeV");
            return (Criteria) this;
        }

        public Criteria andGazeVGreaterThan(Integer value) {
            addCriterion("gaze_v >", value, "gazeV");
            return (Criteria) this;
        }

        public Criteria andGazeVGreaterThanOrEqualTo(Integer value) {
            addCriterion("gaze_v >=", value, "gazeV");
            return (Criteria) this;
        }

        public Criteria andGazeVLessThan(Integer value) {
            addCriterion("gaze_v <", value, "gazeV");
            return (Criteria) this;
        }

        public Criteria andGazeVLessThanOrEqualTo(Integer value) {
            addCriterion("gaze_v <=", value, "gazeV");
            return (Criteria) this;
        }

        public Criteria andGazeVIn(List<Integer> values) {
            addCriterion("gaze_v in", values, "gazeV");
            return (Criteria) this;
        }

        public Criteria andGazeVNotIn(List<Integer> values) {
            addCriterion("gaze_v not in", values, "gazeV");
            return (Criteria) this;
        }

        public Criteria andGazeVBetween(Integer value1, Integer value2) {
            addCriterion("gaze_v between", value1, value2, "gazeV");
            return (Criteria) this;
        }

        public Criteria andGazeVNotBetween(Integer value1, Integer value2) {
            addCriterion("gaze_v not between", value1, value2, "gazeV");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(Boolean value) {
            addCriterion("enabled =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(Boolean value) {
            addCriterion("enabled <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(Boolean value) {
            addCriterion("enabled >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enabled >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(Boolean value) {
            addCriterion("enabled <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("enabled <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Boolean> values) {
            addCriterion("enabled in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Boolean> values) {
            addCriterion("enabled not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("modified_time is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("modified_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("modified_time =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("modified_time <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("modified_time >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_time >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("modified_time <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("modified_time <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("modified_time in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("modified_time not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("modified_time between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("modified_time not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vision_check_record
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 04 15:29:42 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vision_check_record
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}