package org.vision.wechat.persistence.model;

import java.io.Serializable;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wx_client_vision_client
 */
@Data
public class WxClientVisionClientPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_client_vision_client.id
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_client_vision_client.wx_client_id
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    private String wxClientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_client_vision_client.vision_client_id
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    private String visionClientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    private static final long serialVersionUID = 1L;
}