spring:
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    context-path: /vision
---
spring:
  profiles: dev
  application: 
    name: service-provider
  redis:
    database: 0
    host: www.yshjh.com
    port: 6379
    password: e7KD4na37hPtRUUR
    jedis:
      pool:
        max-active: 100
        max-idle: 8
        max-wait: 2000ms
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://www.yshjh.com:3306/vision?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  swagger:
    show: true
  cloud1:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main: 
    allow-bean-definition-overriding: true     
        
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml    
wx:
  config:
    appid: wx499efff7ae899e05
    secret: 771e7ad9a65eea4b1e73238e25e7472c    
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
swagger:
  enabled: true
  title: swagger-vision-admin
  description: vision-admin api docs
  version: 0.1-SNAPSHOT
  license:
  licenseUrl:
  termsOfServiceUrl:
  contact:
    name: Jimmy Xu
    url:
    email: 292208860@qq.com
  base-package: org.vision.admin_service.controller
  # 分组策略
#  docket:
#    apiForMe:
#      title: Myself
#      description: 开放给自己的接口
#      base-path: /api/myself/**
#    apiForOthers:
#      title: Others
#      description: 作为其他人的接口
#      base-path: /api/others/**
  # 公共参数
#  global-operation-parameters[0]:
#    name: TOKEN
#    description: 鉴权
#    modelRef: string
#    parameterType: header
#    # 公共参数写成requierd, 对于不需要登录的接口随便写一个字符串即可
#    required: true
#  # 通用返回错误码
#  apply-default-response-messages: true
#  global-response-message.get[0]:
#    code: 401
#    message: 401错误
#  global-response-message.get[1]:
#    code: 500
#    message: 后端错误
#    modelRef: ERROR
