package org.vision.wechat.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.vision.wechat.persistence.model.WxClientPO;
import org.vision.wechat.persistence.model.WxClientPOExample;

@Mapper
public interface WxClientPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    long countByExample(WxClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    int deleteByExample(WxClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    int insert(WxClientPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    int insertSelective(WxClientPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    List<WxClientPO> selectByExample(WxClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    WxClientPO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") WxClientPO record, @Param("example") WxClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    int updateByExample(@Param("record") WxClientPO record, @Param("example") WxClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    int updateByPrimaryKeySelective(WxClientPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client
     *
     * @mbg.generated Mon Mar 04 15:29:41 CST 2019
     */
    int updateByPrimaryKey(WxClientPO record);
}