package org.vision.wechat.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.vision.wechat.persistence.model.WxClientVisionClientPO;
import org.vision.wechat.persistence.model.WxClientVisionClientPOExample;

@Mapper
public interface WxClientVisionClientPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    long countByExample(WxClientVisionClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    int deleteByExample(WxClientVisionClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    int insert(WxClientVisionClientPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    int insertSelective(WxClientVisionClientPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    List<WxClientVisionClientPO> selectByExample(WxClientVisionClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    WxClientVisionClientPO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") WxClientVisionClientPO record, @Param("example") WxClientVisionClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    int updateByExample(@Param("record") WxClientVisionClientPO record, @Param("example") WxClientVisionClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    int updateByPrimaryKeySelective(WxClientVisionClientPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_client_vision_client
     *
     * @mbg.generated Mon Mar 04 15:29:42 CST 2019
     */
    int updateByPrimaryKey(WxClientVisionClientPO record);
}